version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: RouteMK
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/RouteMK
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: jana12345
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
    networks:
      - mynetwork

  db:
    image: postgres:16
    container_name: RouteMK_db
    restart: always
    environment:
      POSTGRES_DB: RouteMK
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - mynetwork
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/RouteMK.sql:/docker-entrypoint-initdb.d/RouteMK.sql

networks:
  mynetwork:
    driver: bridge

volumes:
  postgres_data:
    driver: local